export {default as Faqs} from "./Faqs";
export {default as Team} from "./Team";
export {default as About} from "./About";
export {default as Navbar} from "./Navbar";
export {default as Footer} from "./Footer";
export {default as Measure} from "./Measure";
export {default as Service} from "./Services";
export {default as Herobanner} from "./Herobanner";
export {default as Testimonials} from "./Testimonials";